[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "poke-ckks"
version = "0.1.0"
description = "Homomorphic encrypted dot product search using CKKS."
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "Igor Peric" }
]
dependencies = [
    "Pyfhel>=3.4",
    "numpy>=1.24"
]

[project.optional-dependencies]
test = [
    "pytest>=8",
    "sentence-transformers>=2.2.0",
    "faiss-cpu>=1.7.4",  # For ANN search
]

[tool.setuptools.packages.find]
where = ["src"]
